-
-- TS_DBAX_I  (Tablespace) 
--
CREATE TABLESPACE TS_DBAX_I DATAFILE 
  '....ts_dbaxi01.dbf' SIZE 100M AUTOEXTEND OFF
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

--
-- TS_DBAX_D  (Tablespace) 
--
CREATE TABLESPACE TS_DBAX_D DATAFILE 
  '....ts_dbaxd01.dbf' SIZE 200M AUTOEXTEND OFF
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE USER dbax IDENTIFIED BY password DEFAULT TABLESPACE ts_dbax_d
   TEMPORARY TABLESPACE temp ACCOUNT UNLOCK  PROFILE DEFAULT;
   
  GRANT CREATE SESSION, CREATE TABLE, CREATE PROCEDURE,
  CREATE SEQUENCE TO dbax;
  
  GRANT Execute on DBMS_CRYPTO to dbax;
  
  GRANT CREATE TYPE TO dbax;

  grant create public synonym, drop public synonym to dbax;
  
  
  ALTER USER dbax QUOTA UNLIMITED ON TS_dbax_I;
  ALTER USER dbax QUOTA UNLIMITED ON TS_dbax_D;  
  



