--
-- WDX_AUTH_SCHEMES  (Table) 
--
--  Dependencies: 
--   WDX_APPLICATIONS (Table)
--
CREATE TABLE WDX_AUTH_SCHEMES
(
  APPID          VARCHAR2(50 BYTE)              NOT NULL,
  SCHEME_NAME    VARCHAR2(255 BYTE)             NOT NULL,
  SCHEME_TYPE    VARCHAR2(255 BYTE)             NOT NULL,
  SCHEME         VARCHAR2(4000 BYTE)            NOT NULL,
  ERROR_MESSAGE  VARCHAR2(4000 BYTE)                NULL,
  COMMENTS       VARCHAR2(4000 BYTE)                NULL,
  CREATED_BY     VARCHAR2(100 BYTE)             DEFAULT -1                    NOT NULL,
  CREATED_DATE   DATE                           DEFAULT SYSDATE               NOT NULL,
  MODIFIED_BY    VARCHAR2(100 BYTE)             DEFAULT -1                    NOT NULL,
  MODIFIED_DATE  DATE                           DEFAULT SYSDATE               NOT NULL
);

COMMENT ON TABLE WDX_AUTH_SCHEMES IS 'Authentication schemes: User authentication schemes';

COMMENT ON COLUMN WDX_AUTH_SCHEMES.SCHEME_NAME IS 'Scheme Name, Primary Key';

COMMENT ON COLUMN WDX_AUTH_SCHEMES.SCHEME_TYPE IS 'Seheme Type, can be: Accounts, Custom, LDAP.';


--
-- WDX_AUTH_SCHEMES1_PK  (Index) 
--
--  Dependencies: 
--   WDX_AUTH_SCHEMES (Table)
--
CREATE UNIQUE INDEX WDX_AUTH_SCHEMES1_PK ON WDX_AUTH_SCHEMES
(APPID, SCHEME_NAME);


-- 
-- Non Foreign Key Constraints for Table WDX_AUTH_SCHEMES 
-- 
ALTER TABLE WDX_AUTH_SCHEMES ADD (
  CONSTRAINT WDX_AUTH_SCHEMES1_PK
 PRIMARY KEY
 (APPID, SCHEME_NAME));


-- 
-- Foreign Key Constraints for Table WDX_AUTH_SCHEMES 
-- 
ALTER TABLE WDX_AUTH_SCHEMES ADD (
  CONSTRAINT WDX_AUTH_SCHEMES_APPID_FK 
 FOREIGN KEY (APPID) 
 REFERENCES WDX_APPLICATIONS (APPID));


