CREATE TABLE WDX_AUTH_SCHEMES
(
  NAME           VARCHAR2(255 BYTE)             NOT NULL,
  TYPE           VARCHAR2(255 BYTE)             NOT NULL,
  SCHEME         VARCHAR2(4000 BYTE)            NOT NULL,
  DESCRIPTION    VARCHAR2(300 BYTE)                 NULL,
  CREATED_BY     VARCHAR2(100 BYTE)             DEFAULT -1                    NOT NULL,
  CREATED_DATE   DATE                           DEFAULT SYSDATE               NOT NULL,
  MODIFIED_BY    VARCHAR2(100 BYTE)             DEFAULT -1                    NOT NULL,
  MODIFIED_DATE  DATE                           DEFAULT SYSDATE               NOT NULL
);

COMMENT ON TABLE WDX_AUTH_SCHEMES IS 'Authentication schemes';

COMMENT ON COLUMN WDX_AUTH_SCHEMES.NAME IS 'Scheme Name, Primary Key';

COMMENT ON COLUMN WDX_AUTH_SCHEMES.TYPE IS 'Seheme Type.';


CREATE UNIQUE INDEX WDX_AUTH_SCHEMES_PK ON WDX_AUTH_SCHEMES
(NAME);


ALTER TABLE WDX_AUTH_SCHEMES ADD (
  CONSTRAINT WDX_AUTH_SCHEMES_PK
 PRIMARY KEY
 (NAME));

